"""BOX 字段名"""
BOX_CLASS_FIELD_NAME = 'TYPE_FONC'
BOX_CODE_FIELD_NAME = 'CODE'
BOX_TYPE_FIELD_NAME = 'CAPACITE'

"""CABLE 字段名"""
CABLE_CLASS_FIELD_NAME = 'TYPE_FONC'
CABLE_CODE_FIELD_NAME = 'CODE'
CABLE_TYPE_FIELD_NAME = 'CAPACITE'
CABLE_LEVEL_FIELD_NAME = 'level'
CABLE_ORIGIN_FIELD_NAME = 'ORIGINE'
CABLE_EXTREMITY_FIELD_NAME = 'EXTREMITE'
CABLE_SECTION_FIELD_NAME = 'SECTION'
CABLE_LENGTH_FIELD_NAME = 'LGR_CARTO'